services:
  cron:
    build:
      context: .
      dockerfile: apps/cron/Dockerfile
    container_name: gsb-cron
    restart: always
    env_file:
      - apps/cron/.env
    networks:
      - internal
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: gsb-api
    restart: always
    env_file:
      - apps/api/.env
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
      cron:
        condition: service_started
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: gsb-web
    restart: always
    env_file:
      - apps/web/.env
    ports:
      - "3000:3000"
    networks:
      - internal
    depends_on:
      api:
        condition: service_started
networks:
  internal:
    driver: bridge
